### ISSUE TITLE
ローカルでのテスト実行方法がわからない

### ISSUE THREAD

**Issue by yuyan7** [yuya-painapo/want_to#48]
2) トップ画面を開く トップ画面にアクセスする もしトップ画面を表示する -> ならばトップ画面が表示されていること
     Got 0 failures and 2 other errors:

```
 2.1) Failure/Error: もし トップ画面を表示する
      Cliver::Dependency::NotFound:
        Could not find an executable ["phantomjs"] on your path.
      # spec/steps/toppage_steps.rb:5:in `block in <top (required)>'
      # ./spec/features/toppage.feature:5:in `run_step'
      # ./spec/features/toppage.feature:6:in `block (4 levels) in run_feature'
      # ./spec/features/toppage.feature:5:in `each'
      # ./spec/features/toppage.feature:5:in `block (3 levels) in run_feature'
      # ./spec/features/toppage.feature:5:in `トップ画面を表示する'

 2.2) Failure/Error: Unable to find matching line from backtrace
      Cliver::Dependency::NotFound:
        Could not find an executable ["phantomjs"] on your path.
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/cliver-0.3.2/lib/cliver/dependency.rb:143:in `raise_not_found!'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/cliver-0.3.2/lib/cliver/dependency.rb:116:in `detect!'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/cliver-0.3.2/lib/cliver.rb:24:in `detect!'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/client.rb:36:in `initialize'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/client.rb:14:in `new'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/client.rb:14:in `start'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/driver.rb:42:in `client'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/driver.rb:25:in `browser'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/driver.rb:177:in `reset!'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/capybara-2.5.0/lib/capybara/session.rb:108:in `reset!'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/capybara-2.5.0/lib/capybara.rb:259:in `block in reset_sessions!'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/capybara-2.5.0/lib/capybara.rb:259:in `each'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/capybara-2.5.0/lib/capybara.rb:259:in `reset_sessions!'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/capybara-2.5.0/lib/capybara/rspec.rb:21:in `block (2 levels) in <top (required)>'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:364:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:520:in `each'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:607:in `block in run_example_hooks_for'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:606:in `each'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:606:in `run_example_hooks_for'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:477:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:437:in `run_after_example'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:221:in `block in run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-rails-3.3.3/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:389:in `execute_with'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/bin/rspec:23:in `load'
      # /Users/yuya/Develop/want_to/vendor/bundle/ruby/2.2.0/bin/rspec:23:in `<main>'
      # 
      #   Showing full backtrace because every line was filtered out.
      #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
      #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

エラーログ
phantomjsがないって言われている？

**Comment by yuyan7** [comment]
homebrewでphantomjsをインストールしようとした時のエラーログ
環境 : MacOSX 10.11

yuya@MacBook-Pro:want_to (deleted_movie $%)$ brew install phantomjs
phantomjs: OS X Yosemite or older is required.
Error: An unsatisfied requirement failed this build.
elcapitanにまだ対応していない？

**Comment by hogehiga** [comment]
El Capitanに対応してないっぽいですね。 https://github.com/Homebrew/homebrew/issues/44525
他の手段としてはnpm使ってインストールするとかでしょうか。

**Comment by hogehiga** [comment]
自分のリポジトリにtravis-CI仕掛けてそれで対処するそうなのでこのIssueはクローズします。
